import { db } from "../config/firebase-config.js";
import { collection, addDoc } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";

const productosPurina = [
    { nombre: "CAT CHOW GATO AD. CARNE O PESCADO 15KG", precio: 65700, marca: "Purina" },
    { nombre: "CAT CHOW GATITO 15KG", precio: 72000, marca: "Purina" },
    { nombre: "CAT CHOW GATITO 500G", precio: 3580, marca: "Purina" },
    { nombre: "CAT CHOW GATITO 1KG", precio: 6430, marca: "Purina" },
    { nombre: "CAT CHOW ESTERELIZADO 15KG", precio: 74600, marca: "Purina" },
    { nombre: "CAT CHOW ESTERELIZADO 1KG", precio: 6690, marca: "Purina" },
    { nombre: "CAT CHOW ADULTO 500G", precio: 3230, marca: "Purina" },
    { nombre: "CAT CHOW ADULTO 1KG", precio: 5890, marca: "Purina" },
    { nombre: "CAT CHOW ADULTO 3KG", precio: 14940, marca: "Purina" },
    { nombre: "CAT CHOW ADULTO 8KG", precio: 38370, marca: "Purina" },
    { nombre: "FELIX GATO ADULTO 15KG", precio: 57240, marca: "Purina" },
    { nombre: "FELIX GATO GATITO 15KG", precio: 62850, marca: "Purina" },
    { nombre: "FELIX GATO ADULTO 1KG", precio: 5100, marca: "Purina" },
    { nombre: "FELIX GATO ADULTO 3KG", precio: 12980, marca: "Purina" },
    { nombre: "FELIX GATO GATITO 1KG", precio: 5660, marca: "Purina" },
    { nombre: "FELIX GATO GATITO 500G", precio: 2910, marca: "Purina" },
    { nombre: "DOG CHOW CACHORRO PEQUEÑO 20KG", precio: 59570, marca: "Purina" },
    { nombre: "DOG CHOW CACHORRO PEQUEÑO 1.5KG", precio: 5500, marca: "Purina" },
    { nombre: "DOG CHOW CACHORRO PEQUEÑO 3KG", precio: 10020, marca: "Purina" },
    { nombre: "DOG CHOW CACHORRO MEDIANOS 20KG", precio: 55860, marca: "Purina" },
    { nombre: "DOG CHOW CACHORRO MEDIANOS 1.5KG", precio: 5260, marca: "Purina" },
    { nombre: "DOG CHOW CACHORRO MEDIANO 3KG", precio: 9580, marca: "Purina" },
    { nombre: "DOG CHOW CACHORRO MEDIANO 8KG", precio: 23270, marca: "Purina" },
    { nombre: "DOG CHOW ADULTO PEQUEÑO 20KG", precio: 54800, marca: "Purina" },
    { nombre: "DOG CHOW ADULTO PEQUEÑO 1.5KG", precio: 5100, marca: "Purina" },
    { nombre: "DOG CHOW ADULTO PEQUEÑO 3KG", precio: 9300, marca: "Purina" },
    { nombre: "DOG CHOW ADULTO PEQUEÑO 8KG", precio: 22590, marca: "Purina" },
    { nombre: "DOG CHOW ADULTO MEDIANOS 20KG", precio: 51300, marca: "Purina" },
    { nombre: "DOG CHOW ADULTO MEDIANOS 1.5KG", precio: 4830, marca: "Purina" },
    { nombre: "DOG CHOW ADULTO MEDIANOS 3KG", precio: 8800, marca: "Purina" },
    { nombre: "DOG CHOW ADULTO MEDIANOS 8KG", precio: 21400, marca: "Purina" },
    { nombre: "DOG CHOW ADULTO MEDIANOS 15KG", precio: 38420, marca: "Purina" },
    { nombre: "DOG CHOW EDAD MADURA 20KG", precio: 56430, marca: "Purina" },
    { nombre: "DOG CHOW EDAD MADURA 3KG", precio: 9670, marca: "Purina" },
    { nombre: "GATI PESCADO O CARNE 15KG", precio: 38680, marca: "Purina" },
    { nombre: "GATI PESCADO O CARNE 500G", precio: 1790, marca: "Purina" },
    { nombre: "GATI PESCADO O CARNE 1KG", precio: 3440, marca: "Purina" },
    { nombre: "GATI PESCADO O CARNE 3KG", precio: 9640, marca: "Purina" },
    { nombre: "BONELO ADULTO 20KG", precio: 41340, marca: "Purina" },
    { nombre: "BONELO CACHORRO 15KG", precio: 32840, marca: "Purina" },
    { nombre: "BONELO GATO 15KG", precio: 47690, marca: "Purina" },
    { nombre: "BONZO 21KG", precio: 29680, marca: "Purina" },
    { nombre: "DOGUI ADULTO 21KG", precio: 37100, marca: "Purina" },
    { nombre: "DOGUI ADULTO 1.5KG", precio: 3910, marca: "Purina" },
    { nombre: "DOGUI ADULTO 3KG", precio: 6940, marca: "Purina" },
    { nombre: "DOGUI ADULTO 8KG", precio: 16050, marca: "Purina" },
    { nombre: "DOGUI ADULTO 15KG", precio: 28510, marca: "Purina" },
    { nombre: "DOGUI CACHORRO 1.5KG", precio: 4250, marca: "Purina" },
    { nombre: "DOGUI CACHORRO 3KG", precio: 7640, marca: "Purina" },
    { nombre: "DOGUI CACHORRO 8KG", precio: 17700, marca: "Purina" },
    { nombre: "DOGUI CACHORRO 15KG", precio: 31470, marca: "Purina" },
    { nombre: "DOGUI CACHORRO 21KG", precio: 40270, marca: "Purina" },
    { nombre: "EXCELLENT PERRO PUPPY SMALL 15KG", precio: 63180, marca: "Purina" },
    { nombre: "EXCELLENT PUPPY MEDIANOS Y GRANDE 15KG", precio: 61230, marca: "Purina" },
    { nombre: "EXCELLENT PUPPY MEDIANOS Y GRANDE 20KG", precio: 74800, marca: "Purina" },
    { nombre: "EXCELLENT ADULTO SMALL 15KG", precio: 57860, marca: "Purina" },
    { nombre: "EXCELLENT ADULTO MEDIANO Y GRANDE 15KG", precio: 55500, marca: "Purina" },
    { nombre: "EXCELLENT ADULTO MEDIANO Y GRANDE 20KG", precio: 65970, marca: "Purina" },
    { nombre: "EXCELLENT SEÑIOR +7 15KG", precio: 61060, marca: "Purina" },
    { nombre: "EXCELLENT REDUCE CALORIAS 15KG", precio: 63870, marca: "Purina" },
    { nombre: "EXCELLENT SKIN CARE CORDERO 15KG", precio: 59980, marca: "Purina" },
    { nombre: "EXCELLENT PUPPY FORMULA 20KG", precio: 55690, marca: "Purina" },
    { nombre: "EXCELLENT ADULTO FORMULA 20KG", precio: 51720, marca: "Purina" },
    { nombre: "EXCELLENT GATO KITTEN 7.5KG", precio: 55930, marca: "Purina" },
    { nombre: "EXCELLENT GATO ADULTO 7.5KG", precio: 50450, marca: "Purina" },
    { nombre: "EXCELLENT GATO ADULTO 15KG", precio: 98080, marca: "Purina" },
    { nombre: "EXCELLENT GATO URINARY 7.5KG", precio: 58510, marca: "Purina" },
    { nombre: "EXCELLENT GATO URINARY 15KG", precio: 112470, marca: "Purina" },
    { nombre: "EXCELLENT GATO ESTERELIZADO 7.5KG", precio: 58510, marca: "Purina" },
    { nombre: "EXCELLENT GATO MANTENIMIENTO 15KG", precio: 71580, marca: "Purina" },
    { nombre: "PRO PLAN PUPPY RAZA PEQUEÑAS 1KG", precio: 11190, marca: "Purina" },
    { nombre: "PRO PLAN PUPPY RAZAS PEQUEÑAS 7.5KG", precio: 60920, marca: "Purina" },
    { nombre: "PRO PLAN PUPPY RAZAS PEQUEÑAS 12KG", precio: 83530, marca: "Purina" },
    { nombre: "PRO PLAN PUPPY RAZAS MEDIANAS 15KG", precio: 99620, marca: "Purina" },
    { nombre: "PRO PLAN PUPPY RAZAS PEQUEÑAS 3KG", precio: 30700, marca: "Purina" },
    { nombre: "PRO PLAN ADULTO RAZA PEQUEÑA 1KG", precio: 10200, marca: "Purina" },
    { nombre: "PRO PLAN ADULTO RAZA PEQUEÑA 3KG", precio: 27830, marca: "Purina" },
    { nombre: "PRO PLAN ADULTO RAZA PEQUEÑA 7.5KG", precio: 57800, marca: "Purina" },
    { nombre: "PRO PLAN ADULTO RAZA PEQUEÑA 12KG", precio: 75896, marca: "Purina" },
    { nombre: "PRO PLAN ADULTO MEDIANOS 15KG", precio: 90600, marca: "Purina" },
    { nombre: "PRO PLAN ADULTO MEDIANOS 3KG", precio: 26330, marca: "Purina" },
    { nombre: "PRO PLAN ADULTO GRANDES 15KG", precio: 90600, marca: "Purina" },
    { nombre: "PRO PLAN ADULTO EXIGENT 3KG", precio: 26600, marca: "Purina" },
    { nombre: "PRO PLAN ADULTO EXIGENT 7.5KG", precio: 55290, marca: "Purina" },
    { nombre: "PRO PLAN AD. SMALL REDUCE CALORIAS 1KG", precio: 11690, marca: "Purina" },
    { nombre: "PRO PLAN AD. SMALL REDUCE CALORIAS 3KG", precio: 32300, marca: "Purina" },
    { nombre: "PRO PLAN AD. SMALL REDUCE CALORIAS 7.5KG", precio: 67110, marca: "Purina" },
    { nombre: "PRO PLAN AD. MEDIANOS REDUCE CALORIA 12KG", precio: 83570, marca: "Purina" },
    { nombre: "PRO PLAN AD. MEDIANOS REDUCE CALORIA 3KG", precio: 30900, marca: "Purina" },
    { nombre: "PRO PLAN ACTIVE MIND ADULTO SMALL +7 7.5KG", precio: 64470, marca: "Purina" },
    { nombre: "PRO PLAN ACTIVE MIND ADULTO MEDIANO 15KG", precio: 101700, marca: "Purina" },
    { nombre: "PRO PLAN ACTIVE MIND ADULTO SMALL 3KG", precio: 30170, marca: "Purina" },
    { nombre: "PRO PLAN ACTIVE MIND ADULTO MEDIANO 3KG", precio: 28830, marca: "Purina" },
    { nombre: "PRO PLAN ACTIVE MIND ADULTO SMALL 1KG", precio: 11350, marca: "Purina" },
    { nombre: "PRO PLAN SENSITIVE SKIN ADULTO SMALL 7.5KG", precio: 66680, marca: "Purina" },
    { nombre: "PRO PLAN SENSITIVE SKIN ADULTO SMALL 3KG", precio: 31690, marca: "Purina" },
    { nombre: "PRO PLAN SENSITIVE SKIN AD. MEDIANO 3KG", precio: 30280, marca: "Purina" },
    { nombre: "PRO PLAN SENSITIVE SKIN AD. MEDIANO 12KG", precio: 83470, marca: "Purina" },
    { nombre: "PRO PLAN SENSITIVE SKIN STOMACH SMALL 7.5KG", precio: 67310, marca: "Purina" },
    { nombre: "PRO PLAN SENSITIVE SKIN STOMACH GRAN. 3KG", precio: 33380, marca: "Purina" },
    { nombre: "PRO PLAN SENSITIVE SKIN STOMACH GRAN. 12KG", precio: 87140, marca: "Purina" },
    { nombre: "PRO PLAN GATO KITTEN 3KG", precio: 38750, marca: "Purina" },
    { nombre: "PRO PLAN GATO KITTEN 7.5KG", precio: 84520, marca: "Purina" },
    { nombre: "PRO PLAN GATO ADULTO 1KG", precio: 13200, marca: "Purina" },
    { nombre: "PRO PLAN GATO ADULTO 3KG", precio: 35200, marca: "Purina" },
    { nombre: "PRO PLAN GATO ADULTO 7.5KG", precio: 76600, marca: "Purina" },
    { nombre: "PRO PLAN GATO ADULTO 15KG", precio: 133990, marca: "Purina" },
    { nombre: "PRO PLAN GATO + 7 AÑOS 1KG", precio: 14780, marca: "Purina" },
    { nombre: "PRO PLAN GATO + 7 AÑOS 3KG", precio: 38770, marca: "Purina" },
    { nombre: "PRO PLAN GATO + 7 AÑOS 7.5KG", precio: 82930, marca: "Purina" },
    { nombre: "PRO PLAN GATO URINARY 1KG", precio: 15000, marca: "Purina" },
    { nombre: "PRO PLAN GATO URINARY 3KG", precio: 40400, marca: "Purina" },
    { nombre: "PRO PLAN GATO URINARY 7.5KG", precio: 84200, marca: "Purina" },
    { nombre: "PRO PLAN GATO URINARY 15KG", precio: 143400, marca: "Purina" },
    { nombre: "PRO PLAN GATO ESTERELIZADO 1KG", precio: 15100, marca: "Purina" },
    { nombre: "PRO PLAN GATO ESTERELIZADO 3KG", precio: 41200, marca: "Purina" },
    { nombre: "PRO PLAN GATO ESTERELIZADO 7.5KG", precio: 88200, marca: "Purina" },
    { nombre: "PRO PLAN GATO SENSITIVE SKIN Y STOMACH 1KG", precio: 15900, marca: "Purina" },
    { nombre: "PRO PLAN GATO SENSITIVE SKIN Y STOMACH 3KG", precio: 42530, marca: "Purina" },
    { nombre: "POUCH CAT CHOW GATITOS POLLO x12", precio: 15000, marca: "Purina" },
    { nombre: "POUCH CAT CHOW ESTERELIZADO x12", precio: 15000, marca: "Purina" },
    { nombre: "POUCH CAT CHOW ADULTO PESCADO x12", precio: 15000, marca: "Purina" },
    { nombre: "POUCH CAT CHOW ADULTO POLLO x12", precio: 15000, marca: "Purina" },
    { nombre: "POUCH DOG CHOW FESTIVAL DE POLLO x12", precio: 15000, marca: "Purina" },
    { nombre: "POUCH DOG CHOW CENA PAVO x12", precio: 15000, marca: "Purina" },
    { nombre: "POUCH DOG CHOW CACHORRO POLLO x12", precio: 15000, marca: "Purina" },
    { nombre: "POUCH DOG CHOW ADULTO SMALL PAVO x12", precio: 15000, marca: "Purina" },
    { nombre: "POUCH DOG CHOW CACHO. POLLO Y MZN x12", precio: 15000, marca: "Purina" },
    { nombre: "POUCH DOG CHOW ADUL. SMALL SALMON x12", precio: 15000, marca: "Purina" },
    { nombre: "POUCH DOG CHOW ADUL. SMALL POLLO x12", precio: 15000, marca: "Purina" }
];

async function subirPurinaActualizado() {
    console.log("Cargando Purina con precios de primera columna...");
    for (const p of productosPurina) {
        await addDoc(collection(db, "productos"), p);
    }
    console.log("✅ ¡Listo! Base de datos de Purina actualizada.");
}

subirPurinaActualizado();