import { db } from "../config/firebase-config.js"; 
import { collection, query, where, doc, setDoc, getDocs, deleteDoc } from "firebase/firestore";


const catalogoPurina = [
  { "nombre": "Cat Chow Gato Ad. Carne o Pescado 15kg", "precio": 74500, "marca": "Cat Chow",  "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Gato Adulto Pescado 15kg", "precio": 74500, "marca": "Cat Chow",  "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Gato Adulto Carne  15kg", "precio": 74500, "marca": "Cat Chow",  "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Gatito 15kg", "precio": 86800, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Gatito 500g", "precio": 4900, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Gatito 1kg", "precio": 7820, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Esterilizado 15kg", "precio": 90700, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Esterilizado 1kg", "precio": 9218, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Adulto 500g", "precio": 3950, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Adulto 1kg", "precio": 7200, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Adulto 3kg", "precio": 18200, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Adulto 8kg", "precio": 46620, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Adulto 15kg", "precio": 72820, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Gatito 15kg", "precio": 78840, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Adulto 1kg", "precio": 6970, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Adulto 3kg", "precio": 17800, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Gatito 1kg", "precio": 7690, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Gatito 500g", "precio": 3920, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Pequeño 20kg", "precio": 77200, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Pequeño 1.5kg", "precio": 7600, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Pequeño 3kg", "precio": 13800, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Mediano 20kg", "precio": 76950, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Mediano 1.5kg", "precio": 7120, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Mediano 3kg", "precio": 12950, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Mediano 8kg", "precio": 30910, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Pequeño 20kg", "precio": 68000, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Pequeño 1.5kg", "precio": 6780, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Pequeño 3kg", "precio": 12000, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Pequeño 8kg", "precio": 25060, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Mediano 20kg", "precio": 57970, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Mediano 1.5kg", "precio": 5310, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Mediano 3kg", "precio": 11686, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Mediano 8kg", "precio": 23800, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Mediano 15kg", "precio": 43420, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Edad Madura 20kg", "precio": 74920, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Edad Madura 3kg", "precio": 12852, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Gati Pescado o Carne 15kg", "precio": 54500, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Carne 15kg", "precio": 54500, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Pescado 15kg", "precio": 54500, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Pescado 500g", "precio": 2500, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Carne 500g", "precio": 2500, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Pescado 1kg", "precio": 4826, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Carne 1kg", "precio": 4826, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Carne 3kg", "precio": 13618, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Pescado 3kg", "precio": 13618, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Bonelo Adulto 20kg", "precio": 57000, "marca": "Bonelo", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Bonelo Cachorro 15kg", "precio": 45000, "marca": "Bonelo", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Bonelo Gato 15kg", "precio": 66720, "marca": "Bonelo", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Bonzo 21kg", "precio": 41485, "marca": "Bonzo", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Adulto 21kg", "precio": 51700, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Adulto 1.5kg", "precio": 5450, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Adulto 3kg", "precio": 9780, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Adulto 8kg", "precio": 22700, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Adulto 15kg", "precio": 40270, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Cachorro 1.5kg", "precio": 6030, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Cachorro 3kg", "precio": 9075, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Cachorro 8kg", "precio": 21500, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Cachorro 15kg", "precio": 37500, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Cachorro 21kg", "precio": 56195, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Puppy Small 15kg", "precio": 76780, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Puppy Mediano y Grande 15kg", "precio": 74500, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Puppy Mediano y Grande 20kg", "precio": 91500, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Adulto Small 15kg", "precio": 70280, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Adulto Mediano y Grande 15kg", "precio": 66230, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Adulto Mediano y Grande 20kg", "precio": 80200, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Senior +7 15kg", "precio": 74195, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Reduce Calorias 15kg", "precio": 77600, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Skin Care Cordero 15kg", "precio": 72860, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Puppy Formula 20kg", "precio": 75350, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Adulto Formula 20kg", "precio": 69120, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Gato Kitten 7.5kg", "precio": 67820, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Adulto 7.5kg", "precio": 62090, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Adulto 15kg", "precio": 118200, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Urinary 7.5kg", "precio": 72300, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Urinary 15kg", "precio": 155000, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Esterilizado 7.5kg", "precio": 80600, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Mantenimiento 15kg", "precio": 99000, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Puppy Razas Pequeñas 1kg", "precio": 13900, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Puppy Razas Pequeñas 7.5kg", "precio": 74865, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Puppy Razas Pequeñas 12kg", "precio": 94644, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Puppy Razas Medianas 15kg", "precio": 118470, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Puppy Razas Pequeñas 3kg", "precio": 36245, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Raza Pequeña 1kg", "precio": 12656, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Raza Pequeña 3kg", "precio": 32831, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Raza Pequeña 7.5kg", "precio": 68391, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Raza Pequeña 12kg", "precio": 86550, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Medianos 15kg", "precio": 108580, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Medianos 3kg", "precio": 40600, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Grandes 15kg", "precio": 108580, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Exigent 3kg", "precio": 32052, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Exigent 7.5kg", "precio": 63952, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Small Reduce Calorias 1kg", "precio": 16350, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Small Reduce Calorias 3kg", "precio": 38246, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Small Reduce Calorias 7.5kg", "precio": 78776, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Medianos Reduce Calorias 12kg", "precio": 94440, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Medianos Reduce Calorias 3kg", "precio": 43780, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Active Mind Adulto Small +7 7.5kg", "precio": 72210, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Active Mind Adulto Mediano 15kg", "precio": 114940, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Active Mind Adulto Small 3kg", "precio": 34090, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Active Mind Adulto Mediano 3kg", "precio": 46500, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Active Mind Adulto Small 1kg", "precio": 12820, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Adulto Small 7.5kg", "precio": 75350, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Adulto Small 3kg", "precio": 44320, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Adulto Mediano 3kg", "precio": 34220, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Adulto Mediano 12kg", "precio": 133675, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Stomach Small 7.5kg", "precio": 76070, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Stomach Grande 3kg", "precio": 51448, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Stomach Grande 12kg", "precio": 98470, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Kitten 3kg", "precio": 54834, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Kitten 7.5kg", "precio": 110127, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Adulto 1kg", "precio": 17060, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Adulto 3kg", "precio": 42170, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Adulto 7.5kg", "precio": 91760, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Adulto 15kg", "precio": 173920, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato +7 Años 1kg", "precio": 22954, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato +7 Años 3kg", "precio": 54520, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato +7 Años 7.5kg", "precio": 105230, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Urinary 1kg", "precio": 22180, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Urinary 3kg", "precio": 48390, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Urinary 7.5kg", "precio": 110332, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Urinary 15kg", "precio": 194872, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Esterilizado 1kg", "precio": 27311, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Esterilizado 3kg", "precio": 56454, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Esterilizado 7.5kg", "precio": 120300, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Sensitive Skin & Stomach 1kg", "precio": 19050, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Sensitive Skin & Stomach 3kg", "precio": 50960, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pouch Cat Chow (Caja x12) Gatitos Pollo", "precio": 16400, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pouch Cat Chow (Caja x12) Esterilizado", "precio": 1600, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pouch Cat Chow (Caja x12) Adulto Pescado", "precio": 1600, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pouch Cat Chow (Caja x12) Adulto Pollo", "precio": 1600, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow (Caja x12) Festival de Pollo", "precio": 1600, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow (Caja x12) Cena Pavo", "precio": 1600, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow (Caja x12) Cachorro Pollo", "precio": 1600, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow (Caja x12) Adulto Small Pavo", "precio": 1600, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow (Caja x12) Cachorro Pollo y Manzana", "precio": 1600, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow (Caja x12) Adulto Small Salmón", "precio": 1600, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow (Caja x12) Adulto Small Pollo", "precio": 1600, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" }
];

// 2. BORRAR SOLO LA SECCIÓN PURINA
window.borrarSeccionPurina = async function() {
    if (!confirm("¿Borrar sección Purina?")) return;
    const q = query(collection(db, "catalogo"), where("seccion", "==", "Purina"));
    const snapshot = await getDocs(q);
    await Promise.all(snapshot.docs.map(d => deleteDoc(doc(db, "catalogo", d.id))));
    alert(`Borrados ${snapshot.size} productos.`);
};

// 3. SUBIR TODO EL CATÁLOGO CON LA ESTRUCTURA EXACTA
window.subirTodoCatalogoPurina = async function() {
    try {
        await Promise.all(catalogoPurina.map(async (prod) => {
            const idLimpio = prod.nombre.toLowerCase().replace(/[^a-z0-9]/g, "-");
            await setDoc(doc(db, "catalogo", idLimpio), prod);
        }));
        alert("¡Catálogo Purina subido con éxito!");
    } catch (e) {
        console.error(e);
    }
};


