import { db } from '../config/firebase-config'; 
import { collection, query, where, getDocs, deleteDoc, doc, setDoc } from 'firebase/firestore';

const catalogoPurina = [
    { "nombre": "Cat Chow Gato Ad. Carne o Pescado 15kg", "precio": 74500, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
    { "nombre": "Cat Chow Gato Adulto Carne 15kg", "precio": 74500, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
    { "nombre": "Cat Chow Gato Adulto Pescado 15kg", "precio": 74500, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Gatito 15kg", "precio": 81600, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Gatito 500g", "precio": 3980, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Gatito 1kg", "precio": 7230, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Esterelizado 15kg", "precio": 84270, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Esterelizado 1kg", "precio": 7436, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Adulto 500g", "precio": 3600, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Adulto 1kg", "precio": 6540, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Adulto 3kg", "precio": 16640, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Cat Chow Adulto 8kg", "precio": 42960, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Adulto 15kg", "precio": 64680, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Gatito 15kg", "precio": 71020, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Adulto 1kg", "precio": 5670, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Adulto 3kg", "precio": 14400, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Gatito 1kg", "precio": 6295, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Felix Gato Gatito 500g", "precio": 3250, "marca": "Felix", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Pequeño 20kg", "precio": 67310, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Pequeño 1.5kg", "precio": 6100, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Pequeño 3kg", "precio": 11020, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Medianos 20kg", "precio": 63125, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Medianos 1.5kg", "precio": 5785, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Mediano 3kg", "precio": 10630, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Cachorro Mediano 8kg", "precio": 25820, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Pequeño 20kg", "precio": 61925, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Pequeño 1.5kg", "precio": 5620, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Pequeño 3kg", "precio": 10220, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Pequeño 8kg", "precio": 25060, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Medianos 20kg", "precio": 68120, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Medianos 1.5kg", "precio": 6420, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Medianos 3kg", "precio": 9680, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Medianos 8kg", "precio": 28340, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Adulto Medianos 15kg", "precio": 51076, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Edad Madura 20kg", "precio": 63180, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dog Chow Edad Madura 3kg", "precio": 10750, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Gati Pescado 15kg", "precio": 43720, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Carne 15kg", "precio": 43720, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Pescado 500g", "precio": 1970, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Carne 500g", "precio": 1970, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Carne 1kg", "precio": 3750, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Pescado 1kg", "precio": 3750, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Carne 3kg", "precio": 10510, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Gati Pescado 3kg", "precio": 10510, "marca": "Gati", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Bonelo Adulto 20kg", "precio": 46730, "marca": "Bonelo", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Bonelo Cachorro 15kg", "precio": 37100, "marca": "Bonelo", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Bonelo Gato 15kg", "precio": 53890, "marca": "Bonelo", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Bonzo 21kg", "precio": 33540, "marca": "Bonzo", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Adulto 21kg", "precio": 41930, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Adulto 1.5kg", "precio": 4270, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Adulto 3kg", "precio": 7560, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Adulto 8kg", "precio": 17800, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Adulto 15kg", "precio": 32230, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Cachorro 1.5kg", "precio": 4630, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Cachorro 3kg", "precio": 8320, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Cachorro 8kg", "precio": 19630, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Cachorro 15kg", "precio": 35600, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Dogui Cachorro 21kg", "precio": 45400, "marca": "Dogui", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Perro Puppy Small 15kg", "precio": 71390, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Puppy Medianos y Grande 15kg", "precio": 69190, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Puppy Medianos y Grande 20kg", "precio": 84530, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Adulto Small 15kg", "precio": 65380, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Adulto Mediano y Grande 15kg", "precio": 62720, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Adulto Mediano y Grande 20kg", "precio": 74540, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Senior +7 15kg", "precio": 68995, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Reduce Calorias 15kg", "precio": 72180, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Skin Care Cordero 15kg", "precio": 67780, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Puppy Formula 20kg", "precio": 62930, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Adulto Formula 20kg", "precio": 58450, "marca": "Excellent", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Excellent Gato Kitten 7.5kg", "precio": 63200, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Adulto 7.5kg", "precio": 57000, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Adulto 15kg", "precio": 110830, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Urinary 7.5kg", "precio": 66130, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Urinary 15kg", "precio": 127090, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Esterelizado 7.5kg", "precio": 66130, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Excellent Gato Mantenimiento 15kg", "precio": 80880, "marca": "Excellent", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Puppy Razas Pequeñas 1kg", "precio": 12660, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Puppy Razas Pequeñas 7.5kg", "precio": 72950, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Puppy Razas Pequeñas 12kg", "precio": 89380, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Puppy Razas Medianas 15kg", "precio": 112580, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Puppy Razas Pequeñas 3kg", "precio": 34700, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Raza Pequeña 1kg", "precio": 11500, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Raza Pequeña 3kg", "precio": 31450, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Raza Pequeña 7.5kg", "precio": 65320, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Raza Pequeña 12kg", "precio": 85840, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Medianos 15kg", "precio": 102340, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Medianos 3kg", "precio": 29760, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Grandes 15kg", "precio": 102340, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Exigent 3kg", "precio": 30040, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Adulto Exigent 7.5kg", "precio": 62480, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Ad. Small Reduce Calorias 1kg", "precio": 13200, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Ad. Small Reduce Calorias 3kg", "precio": 36450, "marca": "Pro Plan", "categoria": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Ad. Small Reduce Calorias 7.5kg", "precio": 75840, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Ad. Medianos Reduce Calorias 12kg", "precio": 124598, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Ad. Medianos Reduce Calorias 3kg", "precio": 34940, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Active Mind Adulto Small +7 7.5kg", "precio": 78830, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Active Mind Adulto Mediano 15kg", "precio": 130230, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Active Mind Adulto Small 3kg", "precio": 47450, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Active Mind Adulto Mediano 3kg", "precio": 32580, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Active Mind Adulto Small 1kg", "precio": 14950, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Adulto Small 7.5kg", "precio": 81690, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Adulto Small 3kg", "precio": 35810, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Ad. Mediano 3kg", "precio": 42795, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Ad. Mediano 12kg", "precio": 94320, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Stomach Small 7.5kg", "precio": 85284, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Stomach Grande 3kg", "precio": 37730, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Sensitive Skin Stomach Grande 12kg", "precio": 138469, "marca": "Pro Plan", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Kitten 3kg", "precio": 46420, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Kitten 7.5kg", "precio": 101230, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Adulto 1kg", "precio": 15820, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Adulto 3kg", "precio": 55399, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Adulto 7.5kg", "precio": 99989, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Adulto 15kg", "precio": 160500, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato +7 Años 1kg", "precio": 17700, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato +7 Años 3kg", "precio": 46450, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato +7 Años 7.5kg", "precio": 99340, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Urinary 1kg", "precio": 17970, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Urinary 3kg", "precio": 66400, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Urinary 7.5kg", "precio": 100860, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Urinary 15kg", "precio": 171800, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Esterelizado 1kg", "precio": 18090, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Esterelizado 3kg", "precio": 49360, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Esterelizado 7.5kg", "precio": 105340, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Sensitive Skin y Stomach 1kg", "precio": 20190, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pro Plan Gato Sensitive Skin y Stomach 3kg", "precio": 68830, "marca": "Pro Plan", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pouch Cat Chow (Caja) Gatitos Pollo 12ud", "precio": 1600, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pouch Cat Chow (Caja) Esterelizado 12ud", "precio": 16400, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pouch Cat Chow (Caja) Adulto Pescado 12ud", "precio": 16400, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pouch Cat Chow (Caja) Adulto Pollo 12ud", "precio": 16400, "marca": "Cat Chow", "categoria": "Gato", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow Festival de Pollo 12ud", "precio": 16400, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow Cena Pavo 12ud", "precio": 16400, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow Cachorro Pollo 12ud", "precio": 16400, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow Adulto Small Pavo 12ud", "precio": 16400, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow Cacho. Pollo y Mzn 12ud", "precio": 16400, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow Adul. Small Salmon 12ud", "precio": 16400, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" },
  { "nombre": "Pouch Dog Chow Adul. Small Pollo 12ud", "precio": 16400, "marca": "Dog Chow", "categoria": "Perro", "seccion": "Purina" }
];

// 2. Definir en window para usarlas desde consola
window.borrarSeccionPurina = async function() {
    if (!confirm("¿Borrar sección Purina?")) return;
    const q = query(collection(db, "catalogo"), where("seccion", "==", "Purina"));
    const snapshot = await getDocs(q);
    await Promise.all(snapshot.docs.map(d => deleteDoc(doc(db, "catalogo", d.id))));
    alert(`Borrados ${snapshot.size} productos.`);
};

window.subirTodoCatalogoPurina = async function() {
    try {
        await Promise.all(catalogoPurina.map(async (prod) => {
            const idLimpio = prod.nombre.toLowerCase().replace(/[^a-z0-9]/g, "-");
            await setDoc(doc(db, "catalogo", idLimpio), prod);
        }));
        alert("¡Catálogo Purina subido con éxito!");
    } catch (e) {
        console.error(e);
    }
};


